on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install    
      # - name: Test
      #   run: npm test
      #   env:
      #     CI: true
      - name: show files
        run: ls -la
      - name: Create .env
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".envv2"
          FILE_DATA: "REACT_APP_SPOTIFY_CLIENT_ID=${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}\n
                      REACT_APP_SPOTIFY_CLIENT_SECRET=${{ secrets.REACT_APP_SPOTIFY_CLIENT_SECRET }}\n
                      REACT_APP_SPOTIFY_REFRESH_TOKEN=${{ secrets.REACT_APP_SPOTIFY_REFRESH_TOKEN }}\n
                      REACT_APP_SPOTIFY_ACCESS_KEY=${{ secrets.REACT_APP_SPOTIFY_ACCESS_KEY }}\n"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
          envkey_REACT_APP_SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_SECRET }}
          envkey_REACT_APP_SPOTIFY_REFRESH_TOKEN: ${{ secrets.REACT_APP_SPOTIFY_REFRESH_TOKEN }}
          envkey_REACT_APP_SPOTIFY_ACCESS_KEY: ${{ secrets.REACT_APP_SPOTIFY_ACCESS_KEY }}
          file_name: .env
      - name: show files
        run: ls -la
      - name: show files
        run: cat .env
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        run: aws s3 sync . s3://alexwatto-live --acl public-read
        working-directory: react-github-actions-build
  release:
    runs-on: ubuntu-latest
    # We specify that deploys needs to
    # finish before we create a release
    needs: deploy
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      # Zip the build using external action
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: react-github-actions-release-build.zip
          path: react-github-actions-build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-release-build.zip
          path: react-github-actions-release-build.zip
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: react-github-actions-release-build.zip
          body: https://alexwatto-live.s3.amazonaws.com/index.html
          token: ${{ secrets.GITHUB_TOKEN }}